server:
  port: 8001
mybatis:
  type-aliases-package: com.vsofo.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  #spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dpt?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: dept-provider
#info
info:
  app.name: springcloud
  company.name: vsofo
  author: kyle
